// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzqwvvncrmuxxqusxoww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6cXd2dm5jcm11eHhxdXN4b3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzQ0MTUsImV4cCI6MjA2MDM1MDQxNX0.fhEMC_hUYsjU2qa4bwKVj7uABjcIQ8w9sWp5U4XYNSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);